services:
  tms-app:
    build:
      context: .
      dockerfile: dockerfile
      args:
        ENV_FILE: ${ENV_FILE:-.env.prod}
    restart: unless-stopped
    env_file:
      - ${ENV_FILE:-.env.prod}
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      HOST: 0.0.0.0
      PORT: 4000
      FRONTEND_DIST_DIR: /usr/app/frontend
    ports:
      - "4000:4000"
