import { In, IsNull, type EntityManager } from 'typeorm';

import {
  ClassDiscordBinding,
  Enrollment,
  Attendance,
  FeeRecord,
  Session,
  Topic,
} from '../../../../../entities/index.js';
import { SessionStatus } from '../../../../../entities/enums.js';
import { ClassServiceError } from '../../../../../shared/errors/class.error.js';

function getSessionEndAt(session: Session): Date | null {
  if (!session.end_time) {
    return null;
  }

  const [hours = '0', minutes = '0', seconds = '0'] = session.end_time.split(':');
  const endAt = new Date(session.scheduled_at);
  endAt.setHours(Number(hours), Number(minutes), Number(seconds), 0);
  return endAt;
}

export async function assertClassArchivable(
  manager: EntityManager,
  teacherId: number,
  classId: number,
): Promise<void> {
  const enrollmentRepo = manager.getRepository(Enrollment);
  const topicRepo = manager.getRepository(Topic);
  const classDiscordBindingRepo = manager.getRepository(ClassDiscordBinding);
  const candidateSessions = await manager
    .getRepository(Session)
    .createQueryBuilder('session')
    .where('session.teacher_id = :teacherId', { teacherId })
    .andWhere('session.class_id = :classId', { classId })
    .andWhere('session.status IN (:...statuses)', {
      statuses: [SessionStatus.Scheduled, SessionStatus.InProgress],
    })
    .andWhere('session.end_time IS NOT NULL')
    .andWhere('CURRENT_TIMESTAMP >= session.scheduled_at')
    .getMany();
  const now = new Date();
  const ongoingSessionCount = candidateSessions.filter((session) => {
    const endAt = getSessionEndAt(session);
    return endAt !== null && now < endAt;
  }).length;

  if (ongoingSessionCount > 0) {
    throw new ClassServiceError(
      'Không thể đóng lớp: lớp đang có buổi học diễn ra',
      409,
    );
  }

  const activeEnrollmentCount = await enrollmentRepo.count({
    where: {
      teacher_id: teacherId,
      class_id: classId,
      unenrolled_at: IsNull(),
    },
  });

  if (activeEnrollmentCount > 0) {
    throw new ClassServiceError(
      `Không thể đóng lớp: còn ${activeEnrollmentCount} học sinh đang học trong lớp`,
      409,
    );
  }

  const activeTopicCount = await topicRepo.count({
    where: {
      teacher_id: teacherId,
      class_id: classId,
      closed_at: IsNull(),
    },
  });

  if (activeTopicCount > 0) {
    throw new ClassServiceError(
      `Không thể đóng lớp: còn ${activeTopicCount} chuyên đề chưa đóng`,
      409,
    );
  }

  const linkedDiscordGuildCount = await classDiscordBindingRepo.count({
    where: {
      teacher_id: teacherId,
      class_id: classId,
    },
  });

  if (linkedDiscordGuildCount > 0) {
    throw new ClassServiceError(
      'Không thể đóng lớp: lớp vẫn đang liên kết với Discord guild',
      409,
    );
  }
}

export async function deleteAutoGeneratedSessionsForClass(
  manager: EntityManager,
  teacherId: number,
  classId: number,
): Promise<number> {
  const sessions = await manager.getRepository(Session).find({
    select: { id: true },
    where: {
      teacher_id: teacherId,
      class_id: classId,
      is_manual: false,
    },
  });

  if (sessions.length === 0) {
    return 0;
  }

  const sessionIds = sessions.map((session) => session.id);

  await manager.getRepository(FeeRecord).delete({
    teacher_id: teacherId,
    session_id: In(sessionIds),
  });

  await manager.getRepository(Attendance).delete({
    teacher_id: teacherId,
    session_id: In(sessionIds),
  });

  await manager.getRepository(Session).delete({
    teacher_id: teacherId,
    class_id: classId,
    is_manual: false,
  });

  return sessionIds.length;
}
