import { IsNull, type EntityManager } from 'typeorm';

import {
  DiscordServer,
  Enrollment,
  Session,
  Topic,
} from '../../../../../entities/index.js';
import { SessionStatus } from '../../../../../entities/enums.js';
import { ClassServiceError } from '../../../../../shared/errors/class.error.js';

export async function assertClassArchivable(
  manager: EntityManager,
  teacherId: number,
  classId: number,
): Promise<void> {
  const enrollmentRepo = manager.getRepository(Enrollment);
  const topicRepo = manager.getRepository(Topic);
  const discordServerRepo = manager.getRepository(DiscordServer);
  const ongoingSessionCount = await manager
    .getRepository(Session)
    .createQueryBuilder('session')
    .where('session.teacher_id = :teacherId', { teacherId })
    .andWhere('session.class_id = :classId', { classId })
    .andWhere('session.status IN (:...statuses)', {
      statuses: [SessionStatus.Scheduled, SessionStatus.InProgress],
    })
    .andWhere('session.end_time IS NOT NULL')
    .andWhere('CURRENT_TIMESTAMP >= session.scheduled_at')
    .andWhere('CURRENT_TIMESTAMP < (session.scheduled_at::date + session.end_time)::timestamptz')
    .getCount();

  if (ongoingSessionCount > 0) {
    throw new ClassServiceError(
      'Không thể đóng lớp: lớp đang có buổi học diễn ra',
      409,
    );
  }

  const activeEnrollmentCount = await enrollmentRepo.count({
    where: {
      teacher_id: teacherId,
      class_id: classId,
      unenrolled_at: IsNull(),
    },
  });

  if (activeEnrollmentCount > 0) {
    throw new ClassServiceError(
      `Không thể đóng lớp: còn ${activeEnrollmentCount} học sinh đang học trong lớp`,
      409,
    );
  }

  const activeTopicCount = await topicRepo.count({
    where: {
      teacher_id: teacherId,
      class_id: classId,
      closed_at: IsNull(),
    },
  });

  if (activeTopicCount > 0) {
    throw new ClassServiceError(
      `Không thể đóng lớp: còn ${activeTopicCount} chuyên đề chưa đóng`,
      409,
    );
  }

  const linkedDiscordServerCount = await discordServerRepo.count({
    where: {
      teacher_id: teacherId,
      class_id: classId,
    },
  });

  if (linkedDiscordServerCount > 0) {
    throw new ClassServiceError(
      'Không thể đóng lớp: lớp vẫn đang liên kết với Discord server',
      409,
    );
  }
}

export async function deleteAutoGeneratedSessionsForClass(
  manager: EntityManager,
  teacherId: number,
  classId: number,
): Promise<number> {
  const sessionRows = await manager.query(`
    SELECT id
    FROM sessions
    WHERE teacher_id = $1
      AND class_id = $2
      AND is_manual = FALSE
  `, [teacherId, classId]) as Array<{ id: number }>;

  if (sessionRows.length === 0) {
    return 0;
  }

  const sessionIds = sessionRows.map((row) => row.id);

  await manager.query(`
    DELETE FROM fee_records
    WHERE teacher_id = $1
      AND session_id = ANY($2::int[])
  `, [teacherId, sessionIds]);

  await manager.query(`
    DELETE FROM attendance
    WHERE teacher_id = $1
      AND session_id = ANY($2::int[])
  `, [teacherId, sessionIds]);

  await manager.query(`
    DELETE FROM sessions
    WHERE teacher_id = $1
      AND class_id = $2
      AND is_manual = FALSE
  `, [teacherId, classId]);

  return sessionIds.length;
}
