import type { EntityManager } from 'typeorm';

import { deleteAutoGeneratedSessionsForClass } from './ClassArchiveSupport.js';

export class TypeOrmClassSessionLifecycle {
  constructor(private readonly manager: EntityManager) {}

  deleteAutoGeneratedSessions(teacherId: number, classId: number): Promise<number> {
    return deleteAutoGeneratedSessionsForClass(this.manager, teacherId, classId);
  }
}
