import { Between, type EntityManager, In, IsNull, MoreThanOrEqual } from 'typeorm';
import { type AttendanceRecordSummary, AttendanceSource, AttendanceStatus, type ClassScheduleInput, type ClassScheduleSummary, ClassStatus, type CreateClassInput, type CreateManualSessionInput, SessionStatus, type SessionSummary, type UpdateClassInput, type UpsertSessionAttendanceInput } from '../../../contracts/types.js';
import { HttpError } from '../../../../../shared/errors/HttpError.js';
import { Enrollment } from '../../../../enrollment/infrastructure/persistence/typeorm/entities/enrollment.entity.js';
import { FeeRecord } from '../../../../finance/infrastructure/persistence/typeorm/entities/fee-record.entity.js';
import { ClassDiscordBinding } from '../../../../messaging/infrastructure/persistence/typeorm/entities/class-discord-binding.entity.js';
import { Topic } from '../../../../topic/infrastructure/persistence/typeorm/entities/topic.entity.js';
import { Attendance } from './entities/attendance.entity.js';
import { Session } from './entities/session.entity.js';
import { ClassScheduleMapper, combineDateAndTime } from './Mapper.js';
import { ClassSchedule } from './entities/class-schedule.entity.js';
import { Class } from './entities/class.entity.js';
import { AppDataSource } from '../../../../../infrastructure/database/data-source.js';
import { UpsertSessionAttendanceUseCase } from '../../../application/commands/UpsertSessionAttendanceUseCase.js';
import { syncVoiceAttendanceForSession } from '../../../jobs/voice-attendance-sync.job.js';
import { Student } from '../../../../enrollment/infrastructure/persistence/typeorm/entities/student.entity.js';
import { ArchiveClassUseCase } from '../../../application/commands/ArchiveClassUseCase.js';
import { CreateClassUseCase } from '../../../application/commands/CreateClassUseCase.js';
import { UpdateClassUseCase } from '../../../application/commands/UpdateClassUseCase.js';
import { CancelSessionUseCase } from '../../../application/commands/CancelSessionUseCase.js';
import { CreateManualSessionUseCase } from '../../../application/commands/CreateManualSessionUseCase.js';
import { TypeOrmFinanceFeeSync } from '../../../../finance/infrastructure/persistence/typeorm/Writer.js';

// ClassArchiveSupport.ts
function getSessionEndAt(session: Session): Date | null {
  if (!session.end_time) {
    return null;
  }

  const [hours = '0', minutes = '0', seconds = '0'] = session.end_time.split(':');
  const endAt = new Date(session.scheduled_at);
  endAt.setHours(Number(hours), Number(minutes), Number(seconds), 0);
  return endAt;
}

export async function assertClassArchivable(
  manager: EntityManager,
  teacherId: number,
  classId: number,
): Promise<void> {
  const enrollmentRepo = manager.getRepository(Enrollment);
  const topicRepo = manager.getRepository(Topic);
  const classDiscordBindingRepo = manager.getRepository(ClassDiscordBinding);
  const candidateSessions = await manager
    .getRepository(Session)
    .createQueryBuilder('session')
    .where('session.teacher_id = :teacherId', { teacherId })
    .andWhere('session.class_id = :classId', { classId })
    .andWhere('session.status IN (:...statuses)', {
      statuses: [SessionStatus.Scheduled, SessionStatus.InProgress],
    })
    .andWhere('session.end_time IS NOT NULL')
    .andWhere('CURRENT_TIMESTAMP >= session.scheduled_at')
    .getMany();
  const now = new Date();
  const ongoingSessionCount = candidateSessions.filter((session) => {
    const endAt = getSessionEndAt(session);
    return endAt !== null && now < endAt;
  }).length;

  if (ongoingSessionCount > 0) {
    throw new HttpError(
      'Không thể đóng lớp: lớp đang có buổi học diễn ra',
      409,
    );
  }

  const activeEnrollmentCount = await enrollmentRepo.count({
    where: {
      teacher_id: teacherId,
      class_id: classId,
      unenrolled_at: IsNull(),
    },
  });

  if (activeEnrollmentCount > 0) {
    throw new HttpError(
      `Không thể đóng lớp: còn ${activeEnrollmentCount} học sinh đang học trong lớp`,
      409,
    );
  }

  const activeTopicCount = await topicRepo.count({
    where: {
      teacher_id: teacherId,
      class_id: classId,
      closed_at: IsNull(),
    },
  });

  if (activeTopicCount > 0) {
    throw new HttpError(
      `Không thể đóng lớp: còn ${activeTopicCount} chuyên đề chưa đóng`,
      409,
    );
  }

  const linkedDiscordGuildCount = await classDiscordBindingRepo.count({
    where: {
      teacher_id: teacherId,
      class_id: classId,
    },
  });

  if (linkedDiscordGuildCount > 0) {
    throw new HttpError(
      'Không thể đóng lớp: lớp vẫn đang liên kết với Discord guild',
      409,
    );
  }
}

export async function deleteAutoGeneratedSessionsForClass(
  manager: EntityManager,
  teacherId: number,
  classId: number,
): Promise<number> {
  const sessions = await manager.getRepository(Session).find({
    select: { id: true },
    where: {
      teacher_id: teacherId,
      class_id: classId,
      is_manual: false,
    },
  });

  if (sessions.length === 0) {
    return 0;
  }

  const sessionIds = sessions.map((session) => session.id);

  await manager.getRepository(FeeRecord).delete({
    teacher_id: teacherId,
    session_id: In(sessionIds),
  });

  await manager.getRepository(Attendance).delete({
    teacher_id: teacherId,
    session_id: In(sessionIds),
  });

  await manager.getRepository(Session).delete({
    teacher_id: teacherId,
    class_id: classId,
    is_manual: false,
  });

  return sessionIds.length;
}

// ClassScheduleSupport.ts
const SESSION_GENERATION_HORIZON_DAYS = 180;

function nowStartOfDay(): Date {
  const now = new Date();
  return new Date(now.getFullYear(), now.getMonth(), now.getDate(), 0, 0, 0, 0);
}

function endOfDay(date: Date): Date {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate(), 23, 59, 59, 999);
}

function addDays(date: Date, amount: number): Date {
  const next = new Date(date);
  next.setDate(next.getDate() + amount);
  return next;
}

function dateOnlyString(date: Date): string {
  return [
    date.getFullYear(),
    String(date.getMonth() + 1).padStart(2, '0'),
    String(date.getDate()).padStart(2, '0'),
  ].join('-');
}

function combineDateWithEndTime(date: Date, endTime: string): Date {
  return combineDateAndTime(dateOnlyString(date), endTime);
}

function sessionOverlaps(
  sessionStart: Date,
  sessionEndTime: string,
  candidateStart: Date,
  candidateEndTime: string,
): boolean {
  const sessionEnd = combineDateWithEndTime(sessionStart, sessionEndTime);
  const candidateEnd = combineDateWithEndTime(candidateStart, candidateEndTime);

  return sessionStart < candidateEnd && candidateStart < sessionEnd;
}

function ensureScheduleTimeRange(schedule: ClassSchedule): void {
  if (schedule.end_time <= schedule.start_time) {
    throw new HttpError('end_time must be later than start_time', 400);
  }
}

function scheduleInputsOverlap(left: ClassScheduleInput, right: ClassScheduleInput): boolean {
  return left.day_of_week === right.day_of_week
    && left.start_time < right.end_time
    && right.start_time < left.end_time;
}

function assertNoOverlappingScheduleInputs(schedules: ClassScheduleInput[]): void {
  for (let leftIndex = 0; leftIndex < schedules.length; leftIndex += 1) {
    for (let rightIndex = leftIndex + 1; rightIndex < schedules.length; rightIndex += 1) {
      if (scheduleInputsOverlap(schedules[leftIndex], schedules[rightIndex])) {
        throw new HttpError('Lịch học không được giao nhau', 409);
      }
    }
  }
}

async function assertNoPersistedScheduleOverlap(
  manager: EntityManager,
  teacherId: number,
  schedules: ClassScheduleInput[],
  options?: {
    excludeClassId?: number;
    excludeScheduleId?: number;
  },
): Promise<void> {
  const scheduleRepo = manager.getRepository(ClassSchedule);

  for (const schedule of schedules) {
    const query = scheduleRepo
      .createQueryBuilder('schedule')
      .innerJoin(Class, 'class', 'class.id = schedule.class_id')
      .where('schedule.teacher_id = :teacherId', { teacherId })
      .andWhere('schedule.day_of_week = :dayOfWeek', { dayOfWeek: schedule.day_of_week })
      .andWhere('class.status = :activeStatus', { activeStatus: ClassStatus.Active })
      .andWhere('schedule.start_time < :endTime', { endTime: schedule.end_time })
      .andWhere(':startTime < schedule.end_time', { startTime: schedule.start_time });

    if (options?.excludeClassId !== undefined) {
      query.andWhere('schedule.class_id <> :excludeClassId', { excludeClassId: options.excludeClassId });
    }

    if (options?.excludeScheduleId !== undefined) {
      query.andWhere('schedule.id <> :excludeScheduleId', { excludeScheduleId: options.excludeScheduleId });
    }

    const overlappingSchedule = await query.getOne();

    if (overlappingSchedule) {
      throw new HttpError('Lịch học không được giao nhau', 409);
    }
  }
}

async function assertNoUpcomingSessionOverlapForSchedules(
  manager: EntityManager,
  teacherId: number,
  classId: number,
  schedules: ClassScheduleInput[],
): Promise<void> {
  if (schedules.length === 0) {
    return;
  }

  const now = new Date();
  const startDate = nowStartOfDay();
  const endDate = addDays(startDate, SESSION_GENERATION_HORIZON_DAYS);
  const sessionRepo = manager.getRepository(Session);
  const sessions = await sessionRepo.find({
    where: {
      teacher_id: teacherId,
      scheduled_at: Between(now, endOfDay(endDate)),
    },
  });

  const sessionsToCompare = sessions.filter((session) => (
    !session.isCancelled()
    && session.end_time !== null
    && (session.class_id !== classId || session.is_manual)
  ));

  for (const schedule of schedules) {
    for (let cursor = new Date(startDate); cursor <= endDate; cursor.setDate(cursor.getDate() + 1)) {
      if (cursor.getDay() !== schedule.day_of_week) {
        continue;
      }

      const scheduledAt = combineDateAndTime(dateOnlyString(cursor), schedule.start_time);

      if (scheduledAt < now) {
        continue;
      }

      const overlappingSession = sessionsToCompare.find((session) => (
        session.end_time !== null
        && sessionOverlaps(session.scheduled_at, session.end_time, scheduledAt, schedule.end_time)
      ));

      if (overlappingSession) {
        throw new HttpError('Lịch học bị trùng với buổi học đã có', 409);
      }
    }
  }
}

async function generateSessionsForSchedule(
  manager: EntityManager,
  teacherId: number,
  schedule: ClassSchedule,
): Promise<number> {
  const now = new Date();
  const startDate = nowStartOfDay();
  const endDate = addDays(startDate, SESSION_GENERATION_HORIZON_DAYS);

  if (endDate < startDate) {
    return 0;
  }

  const rangeStart = startDate;
  const rangeEnd = endOfDay(endDate);

  const sessionRepo = manager.getRepository(Session);
  const existingSessions = await sessionRepo.find({
    where: {
      teacher_id: teacherId,
      class_id: schedule.class_id,
      scheduled_at: Between(rangeStart, rangeEnd),
    },
  });

  const existingTimestamps = new Set(existingSessions.map((item) => item.scheduled_at.getTime()));
  const sessionsToCreate: Session[] = [];

  for (let cursor = new Date(startDate); cursor <= endDate; cursor.setDate(cursor.getDate() + 1)) {
    if (cursor.getDay() !== schedule.day_of_week) {
      continue;
    }

    const dateOnly = `${cursor.getFullYear()}-${String(cursor.getMonth() + 1).padStart(2, '0')}-${String(cursor.getDate()).padStart(2, '0')}`;
    const scheduledAt = combineDateAndTime(dateOnly, schedule.start_time);
    const scheduledAtTimestamp = scheduledAt.getTime();

    if (scheduledAt < now) {
      continue;
    }

    if (existingTimestamps.has(scheduledAtTimestamp)) {
      continue;
    }

    sessionsToCreate.push(
      sessionRepo.create({
        teacher_id: teacherId,
        class_id: schedule.class_id,
        scheduled_at: scheduledAt,
        end_time: schedule.end_time,
        status: SessionStatus.Scheduled,
        is_manual: false,
      }),
    );

    existingTimestamps.add(scheduledAtTimestamp);
  }

  if (sessionsToCreate.length > 0) {
    await sessionRepo.save(sessionsToCreate);
  }

  return sessionsToCreate.length;
}

function sessionMatchesSchedule(session: Session, schedule: ClassSchedule): boolean {
  const scheduledTime = [
    String(session.scheduled_at.getHours()).padStart(2, '0'),
    String(session.scheduled_at.getMinutes()).padStart(2, '0'),
    String(session.scheduled_at.getSeconds()).padStart(2, '0'),
  ].join(':');

  return session.scheduled_at.getDay() === schedule.day_of_week
    && scheduledTime === schedule.start_time;
}

export async function reconcileGeneratedSessionsForClass(
  manager: EntityManager,
  teacherId: number,
  classId: number,
): Promise<{ sessions_created: number; sessions_removed: number }> {
  const scheduleRepo = manager.getRepository(ClassSchedule);
  const sessionRepo = manager.getRepository(Session);
  const schedules = await scheduleRepo.find({
    where: {
      teacher_id: teacherId,
      class_id: classId,
    },
  });

  const now = new Date();
  const upcomingGeneratedSessions = await sessionRepo.find({
    where: {
      teacher_id: teacherId,
      class_id: classId,
      status: SessionStatus.Scheduled,
      is_manual: false,
      scheduled_at: MoreThanOrEqual(now),
    },
  });

  const obsoleteSessions = upcomingGeneratedSessions.filter((session) => (
    !schedules.some((schedule) => sessionMatchesSchedule(session, schedule))
  ));
  const scheduleBySessionId = new Map<number, ClassSchedule>();
  upcomingGeneratedSessions.forEach((session) => {
    const schedule = schedules.find((item) => sessionMatchesSchedule(session, item));
    if (schedule) {
      scheduleBySessionId.set(session.id, schedule);
    }
  });
  const sessionsNeedingEndTimeUpdate = upcomingGeneratedSessions.filter((session) => {
    const schedule = scheduleBySessionId.get(session.id);
    return schedule && session.end_time !== schedule.end_time;
  });

  if (obsoleteSessions.length > 0) {
    await sessionRepo.remove(obsoleteSessions);
  }

  if (sessionsNeedingEndTimeUpdate.length > 0) {
    sessionsNeedingEndTimeUpdate.forEach((session) => {
      const schedule = scheduleBySessionId.get(session.id);
      session.end_time = schedule?.end_time ?? session.end_time;
    });
    await sessionRepo.save(sessionsNeedingEndTimeUpdate);
  }

  let sessionsCreated = 0;
  for (const schedule of schedules) {
    sessionsCreated += await generateSessionsForSchedule(manager, teacherId, schedule);
  }

  return {
    sessions_created: sessionsCreated,
    sessions_removed: obsoleteSessions.length,
  };
}

export async function replaceClassSchedules(
  manager: EntityManager,
  teacherId: number,
  classId: number,
  schedules: ClassScheduleInput[],
): Promise<void> {
  assertNoOverlappingScheduleInputs(schedules);
  await assertNoPersistedScheduleOverlap(manager, teacherId, schedules, { excludeClassId: classId });
  await assertNoUpcomingSessionOverlapForSchedules(manager, teacherId, classId, schedules);

  const scheduleRepo = manager.getRepository(ClassSchedule);
  const existingSchedules = await scheduleRepo.find({
    where: {
      teacher_id: teacherId,
      class_id: classId,
    },
  });

  if (existingSchedules.length > 0) {
    await scheduleRepo.remove(existingSchedules);
  }

  if (schedules.length > 0) {
    const schedulesToSave = schedules.map((input) => {
      const schedule = scheduleRepo.create({
        teacher_id: teacherId,
        class_id: classId,
        day_of_week: input.day_of_week,
        start_time: input.start_time,
        end_time: input.end_time,
      });

      ensureScheduleTimeRange(schedule);
      return schedule;
    });

    await scheduleRepo.save(schedulesToSave);
  }

  await reconcileGeneratedSessionsForClass(manager, teacherId, classId);
}

// TypeOrmAttendanceCommandHandlers.ts
export class TypeOrmAttendanceCommandHandlers {
  async upsertSessionAttendance(input: {
    teacherId: number;
    sessionId: number;
    studentId: number;
    attendance: UpsertSessionAttendanceInput;
  }): Promise<AttendanceRecordSummary | null> {
    return AppDataSource.transaction(async (manager) => {
      const attendanceWriter = new TypeOrmAttendanceWriter(manager);
      const finance = new TypeOrmSessionFinanceService(manager);
      const useCase = new UpsertSessionAttendanceUseCase(attendanceWriter, finance);
      return useCase.execute(input);
    });
  }

  syncSessionAttendance(input: {
    teacherId: number;
    sessionId: number;
  }) {
    return syncVoiceAttendanceForSession(input.teacherId, input.sessionId);
  }
}

// TypeOrmAttendanceWriter.ts
export class TypeOrmAttendanceWriter {
  constructor(private readonly manager: EntityManager) {}

  findSessionById(teacherId: number, sessionId: number): Promise<Session | null> {
    return this.manager.getRepository(Session).findOneBy({
      id: sessionId,
      teacher_id: teacherId,
    });
  }

  findClassById(teacherId: number, classId: number): Promise<Class | null> {
    return this.manager.getRepository(Class).findOneBy({
      id: classId,
      teacher_id: teacherId,
    });
  }

  findStudentById(teacherId: number, studentId: number): Promise<Student | null> {
    return this.manager.getRepository(Student).findOneBy({
      id: studentId,
      teacher_id: teacherId,
    });
  }

  findEnrollmentAtSessionTime(
    teacherId: number,
    studentId: number,
    classId: number,
    scheduledAt: Date,
  ): Promise<Enrollment | null> {
    return this.manager
      .getRepository(Enrollment)
      .createQueryBuilder('enrollment')
      .where('enrollment.teacher_id = :teacherId', { teacherId })
      .andWhere('enrollment.student_id = :studentId', { studentId })
      .andWhere('enrollment.class_id = :classId', { classId })
      .andWhere('enrollment.enrolled_at <= :scheduledAt', { scheduledAt })
      .andWhere('(enrollment.unenrolled_at IS NULL OR enrollment.unenrolled_at > :scheduledAt)', { scheduledAt })
      .orderBy('enrollment.enrolled_at', 'DESC')
      .getOne();
  }

  findEnrollmentsAtSessionTime(
    teacherId: number,
    classId: number,
    scheduledAt: Date,
  ): Promise<Enrollment[]> {
    return this.manager
      .getRepository(Enrollment)
      .createQueryBuilder('enrollment')
      .where('enrollment.teacher_id = :teacherId', { teacherId })
      .andWhere('enrollment.class_id = :classId', { classId })
      .andWhere('enrollment.enrolled_at <= :scheduledAt', { scheduledAt })
      .andWhere('(enrollment.unenrolled_at IS NULL OR enrollment.unenrolled_at > :scheduledAt)', { scheduledAt })
      .orderBy('enrollment.enrolled_at', 'DESC')
      .getMany();
  }

  findAttendanceForStudent(
    teacherId: number,
    sessionId: number,
    studentId: number,
  ): Promise<Attendance | null> {
    return this.manager.getRepository(Attendance).findOneBy({
      teacher_id: teacherId,
      session_id: sessionId,
      student_id: studentId,
    });
  }

  findAttendanceBySession(teacherId: number, sessionId: number): Promise<Attendance[]> {
    return this.manager.getRepository(Attendance).find({
      where: {
        teacher_id: teacherId,
        session_id: sessionId,
      },
    });
  }

  create(input: {
    teacher_id: number;
    session_id: number;
    student_id: number;
    status: Attendance['status'];
    source: Attendance['source'];
    overridden_at: Date | null;
    notes: string | null;
  }): Attendance {
    return this.manager.getRepository(Attendance).create(input);
  }

  save(attendance: Attendance): Promise<Attendance> {
    return this.manager.getRepository(Attendance).save(attendance);
  }

  async markBotPresentIfNotManual(input: {
    teacherId: number;
    sessionId: number;
    studentId: number;
  }): Promise<boolean> {
    const repo = this.manager.getRepository(Attendance);
    const existing = await repo.findOneBy({
      teacher_id: input.teacherId,
      session_id: input.sessionId,
      student_id: input.studentId,
    });

    if (!existing) {
      await repo.save(repo.create({
        teacher_id: input.teacherId,
        session_id: input.sessionId,
        student_id: input.studentId,
        status: AttendanceStatus.Present,
        source: AttendanceSource.Bot,
        overridden_at: null,
        notes: null,
      }));
      return true;
    }

    if (
      existing.source === AttendanceSource.Manual
      || existing.status === AttendanceStatus.AbsentExcused
    ) {
      return false;
    }

    existing.status = AttendanceStatus.Present;
    existing.source = AttendanceSource.Bot;
    existing.overridden_at = null;
    await repo.save(existing);
    return true;
  }

  remove(records: Attendance[]): Promise<Attendance[]> {
    return this.manager.getRepository(Attendance).remove(records);
  }
}

// TypeOrmClassArchiveGuard.ts
export class TypeOrmClassArchiveGuard {
  constructor(private readonly manager: EntityManager) {}

  assertArchivable(teacherId: number, classId: number): Promise<void> {
    return assertClassArchivable(this.manager, teacherId, classId);
  }
}

// TypeOrmClassCommandHandlers.ts
export class TypeOrmClassCommandHandlers {
  async createClass(input: {
    teacherId: number;
    name: string;
    feePerSession: string;
    schedules: CreateClassInput['schedules'];
  }) {
    return AppDataSource.transaction(async (manager) => {
      const classSchedules = new TypeOrmClassScheduleService(manager);
      const useCase = new CreateClassUseCase(manager, classSchedules);

      return useCase.execute(input);
    });
  }

  async updateClass(input: {
    teacherId: number;
    classId: number;
    name?: string;
    feePerSession?: string;
    schedules?: UpdateClassInput['schedules'];
  }) {
    return AppDataSource.transaction(async (manager) => {
      const classSchedules = new TypeOrmClassScheduleService(manager);
      const useCase = new UpdateClassUseCase(manager, classSchedules);

      return useCase.execute(input);
    });
  }

  async archiveClass(input: {
    teacherId: number;
    classId: number;
    archivedAt: Date;
  }) {
    return AppDataSource.transaction(async (manager) => {
      const archiveGuard = new TypeOrmClassArchiveGuard(manager);
      const sessionLifecycle = new TypeOrmClassSessionLifecycle(manager);
      const useCase = new ArchiveClassUseCase(manager, archiveGuard, sessionLifecycle);

      return useCase.execute(input);
    });
  }
}

// TypeOrmClassScheduleService.ts
export class TypeOrmClassScheduleService {
  constructor(private readonly manager: EntityManager) {}

  replaceSchedules(teacherId: number, classId: number, schedules: ClassScheduleInput[]): Promise<void> {
    return replaceClassSchedules(this.manager, teacherId, classId, schedules);
  }

  async listSchedules(teacherId: number, classId: number): Promise<ClassScheduleSummary[]> {
    const schedules = await this.manager.getRepository(ClassSchedule).find({
      where: {
        teacher_id: teacherId,
        class_id: classId,
      },
      order: {
        day_of_week: 'ASC',
        start_time: 'ASC',
        end_time: 'ASC',
      },
    });

    return schedules.map((schedule) => ClassScheduleMapper.toSummary(schedule));
  }
}

// TypeOrmClassSessionLifecycle.ts
export class TypeOrmClassSessionLifecycle {
  constructor(private readonly manager: EntityManager) {}

  deleteAutoGeneratedSessions(teacherId: number, classId: number): Promise<number> {
    return deleteAutoGeneratedSessionsForClass(this.manager, teacherId, classId);
  }
}

// TypeOrmSessionCommandHandlers.ts
export class TypeOrmSessionCommandHandlers {
  async createManualSession(input: {
    teacherId: number;
    classId: number;
    session: CreateManualSessionInput;
  }): Promise<SessionSummary> {
    return AppDataSource.transaction(async (manager) => {
      const sessions = new TypeOrmSessionWriter(manager);
      const useCase = new CreateManualSessionUseCase(sessions);
      return useCase.execute(input);
    });
  }

  async cancelSession(input: {
    teacherId: number;
    sessionId: number;
  }): Promise<SessionSummary> {
    return AppDataSource.transaction(async (manager) => {
      const sessions = new TypeOrmSessionWriter(manager);
      const attendance = new TypeOrmAttendanceWriter(manager);
      const finance = new TypeOrmSessionFinanceService(manager);
      const useCase = new CancelSessionUseCase(sessions, attendance, finance);
      return useCase.execute({
        ...input,
        cancelledAt: new Date(),
      });
    });
  }
}

// TypeOrmSessionFinanceService.ts
export type SyncAttendanceFeeRecordInput = {
  teacherId: number;
  sessionId: number;
  studentId: number;
  enrollmentId: number;
  amount: string;
  shouldCharge: boolean;
};

const financeFeeSync = new TypeOrmFinanceFeeSync();

export class TypeOrmSessionFinanceService {
  constructor(private readonly manager: EntityManager) {}

  cancelFeeRecordsForSessions(
    teacherId: number,
    sessionIds: number[],
    cancelledAt?: Date,
  ): Promise<void> {
    return financeFeeSync.cancelFeeRecordsForSessions(this.manager, teacherId, sessionIds, cancelledAt).then(() => {});
  }

  syncAttendanceFeeRecord(input: SyncAttendanceFeeRecordInput): Promise<void> {
    return financeFeeSync.syncAttendanceFeeRecord(this.manager, input);
  }
}

// TypeOrmSessionWriter.ts
function sessionWriterEndOfDay(date: Date): Date {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate(), 23, 59, 59, 999);
}

function combineSessionWriterDateWithEndTime(date: Date, endTime: string): Date {
  const [hours, minutes, seconds] = endTime.split(':').map(Number);
  return new Date(date.getFullYear(), date.getMonth(), date.getDate(), hours, minutes, seconds, 0);
}

function sessionWriterOverlaps(
  sessionStart: Date,
  sessionEndTime: string,
  candidateStart: Date,
  candidateEndTime: string,
): boolean {
  const sessionEnd = combineSessionWriterDateWithEndTime(sessionStart, sessionEndTime);
  const candidateEnd = combineSessionWriterDateWithEndTime(candidateStart, candidateEndTime);

  return sessionStart < candidateEnd && candidateStart < sessionEnd;
}

export class TypeOrmSessionWriter {
  constructor(private readonly manager: EntityManager) {}

  findById(teacherId: number, sessionId: number): Promise<Session | null> {
    return this.manager.getRepository(Session).findOneBy({
      id: sessionId,
      teacher_id: teacherId,
    });
  }

  findClassById(teacherId: number, classId: number): Promise<Class | null> {
    return this.manager.getRepository(Class).findOneBy({
      id: classId,
      teacher_id: teacherId,
    });
  }

  findByTeacherClassAndScheduledAt(
    teacherId: number,
    classId: number,
    scheduledAt: Date,
  ): Promise<Session | null> {
    return this.manager.getRepository(Session).findOneBy({
      teacher_id: teacherId,
      class_id: classId,
      scheduled_at: scheduledAt,
    });
  }

  async hasOverlappingSession(
    teacherId: number,
    scheduledAt: Date,
    endTime: string,
  ): Promise<boolean> {
    const sessions = await this.manager.getRepository(Session).find({
      where: {
        teacher_id: teacherId,
        scheduled_at: Between(
          new Date(scheduledAt.getFullYear(), scheduledAt.getMonth(), scheduledAt.getDate(), 0, 0, 0, 0),
          sessionWriterEndOfDay(scheduledAt),
        ),
      },
    });

    return sessions.some((session) => (
      !session.isCancelled()
      && session.end_time !== null
      && sessionWriterOverlaps(session.scheduled_at, session.end_time, scheduledAt, endTime)
    ));
  }

  create(input: {
    teacher_id: number;
    class_id: number;
    scheduled_at: Date;
    end_time: string;
    status: Session['status'];
    is_manual: boolean;
    cancelled_at: null;
  }): Session {
    return this.manager.getRepository(Session).create(input);
  }

  save(session: Session): Promise<Session> {
    return this.manager.getRepository(Session).save(session);
  }
}
