import type { TypeOrmClassArchiveGuard, TypeOrmClassWriter } from '../../infrastructure/persistence/typeorm/Writer.js';
import type { ArchiveClassCommand, ClassSessionLifecycle, ClassSummary } from '../../contracts/types.js';

export class ArchiveClassUseCase {
  constructor(
    private readonly classes: TypeOrmClassWriter,
    private readonly archiveGuard: TypeOrmClassArchiveGuard,
    private readonly sessionLifecycle: ClassSessionLifecycle,
  ) {}

  async execute(command: ArchiveClassCommand): Promise<ClassSummary> {
    await this.archiveGuard.assertArchivable(command.teacherId, command.classId);

    const savedClass = await this.classes.archiveClass(command);
    await this.sessionLifecycle.deleteAutoGeneratedSessions(
      command.teacherId,
      command.classId,
    );

    return savedClass;
  }
}
