import type { StudentStatus } from '../../enrollment/contracts/types.js';
import type { TopicStatusFilter } from '../../topic/contracts/types.js';

export enum AttendanceSource {
  Bot = 'bot',
  Manual = 'manual',
  System = 'system',
}

export enum AttendanceStatus {
  Present = 'present',
  AbsentExcused = 'absent_excused',
  AbsentUnexcused = 'absent_unexcused',
}

export enum ClassStatus {
  Active = 'active',
  Archived = 'archived',
}

export enum SessionStatus {
  Scheduled = 'scheduled',
  InProgress = 'in_progress',
  Completed = 'completed',
  Cancelled = 'cancelled',
}

export type ClassScheduleInput = {
  day_of_week: number;
  start_time: string;
  end_time: string;
};

export type CreateClassInput = {
  name: string;
  fee_per_session: string;
  schedules: ClassScheduleInput[];
};

export type UpdateClassInput = {
  name?: string;
  fee_per_session?: string;
  schedules?: ClassScheduleInput[];
};

export type ClassListFilters = {
  status?: ClassStatus;
  ready_only?: boolean;
};

export type SessionListFilters = {
  class_id?: number;
  status?: SessionStatus;
  from?: Date;
  to?: Date;
};

export type CreateManualSessionInput = {
  scheduled_at: Date;
  end_time: string;
};

export type ClassSummary = {
  id: number;
  teacher_id: number;
  name: string;
  fee_per_session: string;
  status: ClassStatus;
  created_at: Date;
  archived_at: Date | null;
};

export type ClassSummaryWithSchedules = ClassSummary & {
  schedules: ClassScheduleSummary[];
};

export type ClassScheduleSummary = {
  id: number;
  teacher_id: number;
  class_id: number;
  day_of_week: number;
  start_time: string;
  end_time: string;
};

export type ClassDiscordGuildSummary = {
  id: number;
  teacher_id: number;
  class_id: number;
  discord_guild_id: string;
  name: string | null;
  attendance_voice_channel_id: string | null;
  notification_channel_id: string | null;
};

export type ClassDetailStudentSummary = {
  id: number;
  teacher_id: number;
  full_name: string;
  codeforces_handle: string | null;
  discord_username: string | null;
  discord_user_id: string | null;
  phone: string | null;
  status: StudentStatus;
  enrolled_at: Date;
};

export type ClassDetails = {
  class: ClassSummary;
  schedules: ClassScheduleSummary[];
  discord_guild: ClassDiscordGuildSummary | null;
  active_students: ClassDetailStudentSummary[];
  topics: Array<{
    id: number;
    teacher_id: number;
    class_id: number;
    title: string;
    gym_link: string;
    gym_id: string | null;
    closed_at: Date | null;
    pull_interval_minutes: number;
    last_pulled_at: Date | null;
    created_at: Date;
    status: TopicStatusFilter;
    problems: Array<{
      id: number;
      teacher_id: number;
      topic_id: number;
      problem_index: string;
      problem_name: string | null;
    }>;
    progress: {
      total_students: number;
      total_problems: number;
      solved_count: number;
      completed_students: number;
      average_solved: number;
    };
  }>;
  is_ready: boolean;
};

export type SessionSummary = {
  id: number;
  teacher_id: number;
  class_id: number;
  scheduled_at: Date;
  end_time: string | null;
  status: SessionStatus;
  is_manual: boolean;
  created_at: Date;
  cancelled_at: Date | null;
};

export type AttendanceListFilters = {
  session_id?: number;
  student_id?: number;
  status?: AttendanceStatus;
};

export type SessionAttendanceRow = {
  student_id: number;
  student_name: string;
  student_status: StudentStatus;
  attendance_id: number | null;
  attendance_status: AttendanceStatus | null;
  source: AttendanceSource | null;
  notes: string | null;
  overridden_at: Date | null;
};

export type SessionAttendanceSummary = {
  session: SessionSummary;
  attendance: SessionAttendanceRow[];
};

export type AttendanceRecordSummary = {
  id: number;
  teacher_id: number;
  session_id: number;
  student_id: number;
  status: AttendanceStatus;
  source: AttendanceSource;
  overridden_at: Date | null;
  notes: string | null;
};

export type UpsertSessionAttendanceInput = {
  status: AttendanceStatus;
  notes?: string | null;
};

export type CreateClassCommand = {
  teacherId: number;
  name: string;
  feePerSession: string;
  schedules: CreateClassInput['schedules'];
};

export type UpdateClassCommand = {
  teacherId: number;
  classId: number;
  name?: string;
  feePerSession?: string;
  schedules?: UpdateClassInput['schedules'];
};

export type ClassSessionLifecycle = {
  deleteAutoGeneratedSessions(teacherId: number, classId: number): Promise<number>;
};

export type ArchiveClassCommand = {
  teacherId: number;
  classId: number;
  archivedAt: Date;
};

export type CancelSessionCommand = {
  teacherId: number;
  sessionId: number;
  cancelledAt: Date;
};

export type CreateManualSessionCommand = {
  teacherId: number;
  classId: number;
  session: CreateManualSessionInput;
};

export type UpsertSessionAttendanceCommand = {
  teacherId: number;
  sessionId: number;
  studentId: number;
  attendance: UpsertSessionAttendanceInput;
};
