@startuml
object Teacher
object "Student API" as StudentAPI
object "Student transfer" as StudentTransfer
object "Student storage" as StudentStorage
object "Enrollment storage" as EnrollmentStorage
object "Class access check" as ClassAccessCheck
object "Student guild membership" as StudentGuildMembership
object "Student balance reader" as StudentBalanceReader
object Database <<database>>
Teacher --> StudentAPI : 1: transfer request
StudentAPI --> StudentTransfer : 2: execute
StudentTransfer --> StudentStorage : 3: require active student
StudentStorage --> Database : 4: SELECT student
StudentTransfer --> ClassAccessCheck : 5: ensure active class
StudentTransfer --> EnrollmentStorage : 6: load active enrollment
StudentTransfer --> EnrollmentStorage : 7: close old enrollment
StudentTransfer --> EnrollmentStorage : 8: create new enrollment
StudentTransfer --> StudentGuildMembership : 9: join current class guild if possible
StudentTransfer --> StudentBalanceReader : 10: load balance
StudentTransfer --> StudentAPI : 11: student
@enduml
